### ISSUE TITLE
Duplicate Bash Alias Usage in Ubuntu causes Syntax Error

### ISSUE THREAD

**Issue by vsaw** [cyphunk/humanism.sh#4]
In Ubuntu 14.4 LTS I get the following error message

```
bash: humanism.sh: line 418: syntax error near unexpected token `('
bash: humanism.sh: line 418: `    l () {'
```

I'm running revision 1705c122ca5071c1645749a78e62b693e8ac4a49

**Comment by balbinus** [comment]
Same here. Simply editing the function to another name works. Probably comes from the fact that I already have a bash alias defined on "l" (kinda standard on some distros).

**Comment by vsaw** [comment]
@balbinus Perfect! Removing the `l` alias worked for me to (wasn't using it anyway) :+1:

**Comment by cyphunk** [comment]
sorry for the delay. happy someone resolved it. someone let me know if it's just outright rude to enforce such aliases. this is an experiment anyway

**Comment by vsaw** [comment]
I don´t know the generally accepted way to handle/avoid alias conflicts. So I'm gonna rename the issue to clarify it is not resolved yet.

**Comment by cyphunk** [comment]
`l` alias removed from the current branch. I guess I close? There is another alias that could cause conflicts in some places which is `cc`. If someone things I should remove that as well I will
