### ISSUE TITLE
Option to pass options to ps

### ISSUE THREAD

**Issue by vsaw** [cyphunk/humanism.sh#5]
In cases where more complex filtering is required e.g. `ps --ppid 1234` humanism.sh passes this to egrep and reports

```
egrep: unrecognized option '--ppid'
Usage: egrep [OPTION]... PATTERN [FILE]...
Try 'egrep --help' for more information.
```

Is there any way to pass these unescaped arguments to `ps` directly?

**Comment by cyphunk** [comment]
Yeah the option would be to fall back to vanilla non-aliased ps when there is more than one argument. this is currently done with find for example. 

The code would change to: 

```
    ps () {
            if [ $# -eq 0 ]; then
                    /usr/bin/env ps $FOREST -x -o pid,uid,user,command
            elif [ $# -gt 1 ]; then
                    /usr/bin/env ps $@
            else
                    /usr/bin/env ps $FOREST -a -x -o pid,uid,user,command | grep -v grep | egrep $@
            fi
    }
```

**Comment by vsaw** [comment]
Yeah either that or how `l()` tries to detect arguments https://github.com/cyphunk/humanism.sh/blob/master/humanism.sh#L426.

Don't know which is better though as I'm not sure which `egrep` queries might there be in term so of number of arguments or if they in fact could start with `--`. But I guess in doubt it's better to fall back to regular `ps`.

**Comment by cyphunk** [comment]
resolved. you can ps --ppid <pid> or ps -U <user> or etc
